in:
  type: file
  path_prefix: example/data_for_merge.tsv
  parser:
    type: csv
    delimiter: "\t"
    charset: UTF-8
    newline: CRLF
    null_string: 'NULL'
    skip_header_lines: 0
    comment_line_marker: '#'
    columns:
      - {name: id,  type: long}
      - {name: label, type: string}
      - {name: json_payload, type: json}
filters:
  - type: to_json
    column:
      name: test
      type: string
    skip_if_null: [id]
    merge_mode: true
    merge_priority: [test, json_payload]
    default_timezone: Asia/Tokyo
out:
  type: stdout
